When compiling with gcc-4.7.0 and above, the compiler generates error message:
/scratch/chuangw/mace-fullcontext/lib/test/libtest1.cc: In member function 'void TestMaceKey::BasicMaceKeyTest::test_method()':
/scratch/chuangw/mace-fullcontext/lib/test/libtest1.cc:44:82: error: narrowing conversion of '255' from 'int' to 'char' inside { } is ill-formed in C++11 [-Werror=narrowing]
/scratch/chuangw/mace-fullcontext/lib/test/libtest1.cc:44:82: error: narrowing conversion of '255' from 'int' to 'char' inside { } is ill-formed in C++11 [-Werror=narrowing]
/scratch/chuangw/mace-fullcontext/lib/test/libtest1.cc:44:82: error: narrowing conversion of '255' from 'int' to 'char' inside { } is ill-formed in C++11 [-Werror=narrowing]
/scratch/chuangw/mace-fullcontext/lib/test/libtest1.cc:44:82: error: narrowing conversion of '255' from 'int' to 'char' inside { } is ill-formed in C++11 [-Werror=narrowing]

Switch from char to uint8_t and this problem is gone. (Curiously, how did this narrowing-conversion evaded from previous gcc compiler warnings?)


In file included from /scratch/chuangw/mace/lib/Collections.h:38:0,
                 from /scratch/chuangw/mace/lib/StrUtil.h:44,
                 from /scratch/chuangw/mace/lib/mvector.h:35,
                 from /scratch/chuangw/mace/lib/test/libtest1.cc:5:
/scratch/chuangw/mace/lib/mset.h: In instantiation of 'void mace::set<Key, Serial, LessFcn, Alloc>::push_back(const Key&) [with Key = unsigned int; Serial = mace::SerializeSet<unsigned int>; LessFcn = std::less<unsigned int>; Alloc = std::allocator<unsigned int>]':
/scratch/chuangw/mace/lib/test/libtest1.cc:15:20:   required from here
/scratch/chuangw/mace/lib/mset.h:124:5: error: 'insert' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
/scratch/chuangw/mace/lib/mset.h:124:5: note: declarations in dependent base 'std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> >' are not found by unqualified lookup
/scratch/chuangw/mace/lib/mset.h:124:5: note: use 'this->insert' instead


I keep several versions of gcc builds locally, and I tested them one after the other. The code has no problem up until gcc-4.6.3

I have not yet understanded what have changed since 4.7.0, but here's a simple fix, as indicated in this error message.

--HG--
branch : chuangw/unit_test