I am trying to make fullcontext-mace compile all existing services, but so far there are quite a few that does not compile. The following is a list of services that does not compile:
1. all services under directory FullctxPaxos do not compile because they are not finished.
2. SplitStream does not compile:

In file included from /scratch/chuangw/mace-fullcontext/build/services/SplitStreamMS/SplitStreamMS.cc:10:
/scratch/chuangw/mace-fullcontext/build/services/SplitStreamMS/SplitStreamMS.h: In member function 'virtual void SplitStreamMS_namespace::SplitStreamMSService::printer_MaceTimer::expire()':
/scratch/chuangw/mace-fullcontext/build/services/SplitStreamMS/SplitStreamMS.h:2890: error: 'class SplitStreamMS_namespace::SplitStreamMSService' has no member named 'scheduler_printer'
make[3]: *** [services/SplitStreamMS/CMakeFiles/SplitStreamMS.dir/SplitStreamMS.o] Error 1
make[2]: *** [services/SplitStreamMS/CMakeFiles/SplitStreamMS.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....

3. LUFactorization service does not compile -- this code has not been actively maintained since HPDC'12 deadline.

4. /scratch/chuangw/mace-fullcontext/services/MaceTag/MaceTag-ckcomments.mac does not compile
I believe  this is not an official service so ignore it.

5. FileSync service does not compile -- I broke the compiler code again.
/scratch/chuangw/mace-fullcontext/build/services/FileSync/FileSync.cc: In member function 'void FileSync_namespace::FileSyncService::__async_fn1_getAndStoreHash(const FileS
ync_namespace::__async_at1_getAndStoreHash&)':
/scratch/chuangw/mace-fullcontext/build/services/FileSync/FileSync.cc:6414: error: 'asyncHead' was not declared in this scope
/scratch/chuangw/mace-fullcontext/build/services/FileSync/FileSync.cc:6434: error: 'asyncEventCheck' was not declared in this scope
/scratch/chuangw/mace-fullcontext/build/services/FileSync/FileSync.cc:6438: error: 'asyncPrep' was not declared in this scope
/scratch/chuangw/mace-fullcontext/build/services/FileSync/FileSync.cc:6440: error: 'asyncFinish' was not declared in this scope
/scratch/chuangw/mace-fullcontext/build/services/FileSync/FileSync.cc:6443: error: 'sendAsyncSnapshot' was not declared in this scope
/scratch/chuangw/mace-fullcontext/build/services/FileSync/FileSync.cc:6456: error: 'getNextSeqno' was not declared in this scope